{
 "title": "A3 apps",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Overordnet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Opprettede dødsbo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "altinn_app_oed_estate_created",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-digdir-tt02-rg",
        "resourceName": "digdir-tt02-ai",
        "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
    }
   ]
  },
  {
   "title": "Opprettede erklæringer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "altinn_app_oed_declaration_created",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-digdir-tt02-rg",
        "resourceName": "digdir-tt02-ai",
        "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
    }
   ]
  },
  {
   "title": "Innsendte erklæringer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "altinn_app_oed_declaration_submitted",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-digdir-tt02-rg",
        "resourceName": "digdir-tt02-ai",
        "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
    }
   ]
  },
  {
   "title": "Besluttede skifteformer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "customMetrics\r\n| where name == \"altinn_app_oed_send_correspondence_item\" and customDimensions.itemType == \"ProbateIssuedItem\"\r\n| summarize sum(value)\r\n",
      "resources": [
       "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
      ],
      "resultFormat": "logs",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Status eksterne aktører",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let banks = dynamic({\"984851006\":\"DNB\", \"952706365\":\"SB1 Nord-Norge\", \"920058817\":\"Nordea\", \"920426530\": \"SB1 Østlandet\", \"937901003\": \"SB1 SMN\", \"937895321\": \"SB1 Sør-Norge\"});\r\ncustomMetrics \r\n| where cloud_RoleName == \"oed\" and name == \"altinn_app_oed_dan_request\" and value > 0\r\n| summarize lastrequest=arg_max(timestamp, customDimensions) by dataset=tostring(customDimensions.dataSetName), orgNr=tostring(customDimensions.orgNr)    // Siste request utført pr dataset\r\n| join kind=fullouter ( \r\n  customMetrics \r\n  | where cloud_RoleName == \"oed\" and name == \"altinn_app_oed_dan_error\" and value > 0\r\n  | summarize lasterror=arg_max(timestamp, customDimensions) by dataset=tostring(customDimensions.dataSetName), orgNr=tostring(customDimensions.orgNr)    // Siste error registrert pr dataset\r\n  )\r\n  on dataset\r\n| project dataset, name=iff(isnull(banks[orgNr]), orgNr, banks[orgNr]), lastrequest, lasterror, isOk = isnull(lasterror) or lasterror < lastrequest",
      "resources": [
       "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
      ],
      "resultFormat": "table"
     }
    }
   ]
  },
  {
   "title": "OS og browser",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "requests\r\n| where cloud_RoleName == \"oed\" and url !contains \"/health\" and customDimensions contains \"user.id\"\r\n| summarize value=count() by client_OS, client_Browser\r\n| sort by value\r\n",
      "resources": [
       "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
      ],
      "resultFormat": "table",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Adressebeskyttelse",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "altinn_app_oed_sensitive_heir_estate_closure",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-digdir-tt02-rg",
        "resourceName": "digdir-tt02-ai",
        "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
    }
   ]
  },
  {
   "title": "Arvinger under 18",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "altinn_app_oed_heir_below_legal_age",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-digdir-tt02-rg",
        "resourceName": "digdir-tt02-ai",
        "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
    }
   ]
  },
  {
   "title": "Levende",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [],
      "customNamespace": "Azure.ApplicationInsights",
      "dimensionFilters": [],
      "metricName": "altinn_app_oed_deceased_is_alive",
      "metricNamespace": "microsoft.insights/components",
      "region": "norwayeast",
      "resources": [
       {
        "metricNamespace": "Microsoft.Insights/components",
        "region": "norwayeast",
        "resourceGroup": "monitor-digdir-tt02-rg",
        "resourceName": "digdir-tt02-ai",
        "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
    }
   ]
  },
  {
   "title": "Brukere",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "requests\r\n| where cloud_RoleName == \"oed\" and $__timeFilter(timestamp)\r\n| project userPartyId=tostring(customDimensions.['user.party.id']), \r\n          instanceOwnerPartyId=tostring(customDimensions.['instance.owner.party.id'])\r\n| where isnotempty(userPartyId) and isnotempty(instanceOwnerPartyId)\r\n| summarize ['Unike brukere']=dcount(userPartyId), ['Unike dødsbo']=dcount(instanceOwnerPartyId)\r\n\r\n",
      "resources": [
       "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
      ],
      "resultFormat": "table",
      "timeColumn": "timestamp"
     }
    }
   ]
  },
  {
   "title": "Business detaljer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Opprettede dødsbo",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [],
        "metricName": "altinn_app_oed_estate_created",
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resources": [
         {
          "metricNamespace": "Microsoft.Insights/components",
          "region": "norwayeast",
          "resourceGroup": "monitor-digdir-tt02-rg",
          "resourceName": "digdir-tt02-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      }
     ]
    },
    {
     "title": "Korrespondanse items",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": true,
        "query": "customMetrics\r\n| where name == \"altinn_app_oed_send_correspondence_item\"\r\n| project timestamp, value, customDimensions.itemType\r\n| summarize sum(value) by bin(timestamp, 1m), tostring(customDimensions_itemType)\r\n| project timestamp, sum_value, customDimensions_itemType\r\n| project-rename sum=sum_value\r\n| order by timestamp asc",
        "resources": [
         "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
        ],
        "resultFormat": "time_series",
        "timeColumn": "timestamp"
       }
      }
     ]
    },
    {
     "title": "Utgående arkivering",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [],
        "metricName": "altinn_app_oed_send_archive",
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resources": [
         {
          "metricNamespace": "Microsoft.Insights/components",
          "region": "norwayeast",
          "resourceGroup": "monitor-digdir-tt02-rg",
          "resourceName": "digdir-tt02-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      }
     ]
    },
    {
     "title": "Utgående korrespondanse",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "Azure.ApplicationInsights",
        "dimensionFilters": [],
        "metricName": "altinn_app_oed_send_correspondence",
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resources": [
         {
          "metricNamespace": "Microsoft.Insights/components",
          "region": "norwayeast",
          "resourceGroup": "monitor-digdir-tt02-rg",
          "resourceName": "digdir-tt02-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      }
     ]
    }
   ]
  },
  {
   "title": "Tekniske detaljer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "cloud/roleName",
          "filters": [
           "oed",
           "oed-declaration",
           "oed-events"
          ],
          "operator": "eq"
         }
        ],
        "metricName": "requests/count",
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resources": [
         {
          "metricNamespace": "Microsoft.Insights/components",
          "region": "norwayeast",
          "resourceGroup": "monitor-digdir-tt02-rg",
          "resourceName": "digdir-tt02-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      },
      {
       "azureMonitor": {
        "aggregation": "Count",
        "alias": "Server requests oed-authz",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "requests/count",
        "metricNamespace": "microsoft.insights/components",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "westeurope",
          "resourceGroup": "altinn-digdir-oed-tt02-rg",
          "resourceName": "oed-test-authz-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      }
     ]
    },
    {
     "title": "Håndterte eventer (oed)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": true,
        "query": "customMetrics\r\n| where name == \"altinn_app_oed_handle_event\"\r\n| project timestamp, value, customDimensions.eventType\r\n| summarize sum(value) by bin(timestamp, 1m), tostring(customDimensions_eventType)\r\n| project timestamp, sum_value, customDimensions_eventType\r\n| project-rename _=sum_value\r\n| order by timestamp asc",
        "resources": [
         "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
        ],
        "resultFormat": "time_series",
        "timeColumn": "timestamp"
       }
      }
     ]
    },
    {
     "title": "Server response time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "customNamespace": "microsoft.insights/components",
        "dimensionFilters": [
         {
          "dimension": "cloud/roleName",
          "filters": [
           "oed",
           "oed-events",
           "oed-declaration"
          ],
          "operator": "eq"
         }
        ],
        "metricName": "requests/duration",
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resources": [
         {
          "metricNamespace": "Microsoft.Insights/components",
          "region": "norwayeast",
          "resourceGroup": "monitor-digdir-tt02-rg",
          "resourceName": "digdir-tt02-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      },
      {
       "azureMonitor": {
        "aggregation": "Average",
        "alias": "Server response time oed-authz",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "requests/duration",
        "metricNamespace": "microsoft.insights/components",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "westeurope",
          "resourceGroup": "altinn-digdir-oed-tt02-rg",
          "resourceName": "oed-test-authz-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      }
     ]
    },
    {
     "title": "Publiserte eventer (oed)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": true,
        "query": "customMetrics\r\n| where name == \"altinn_app_oed_post_event\"\r\n| project timestamp, value, customDimensions.eventType\r\n| summarize sum(value) by bin(timestamp, 1m), tostring(customDimensions_eventType)\r\n| project timestamp, sum_value, customDimensions_eventType\r\n| project-rename _=sum_value\r\n| order by timestamp asc",
        "resources": [
         "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
        ],
        "resultFormat": "time_series",
        "timeColumn": "timestamp"
       }
      }
     ]
    },
    {
     "title": "Failed requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "cloud/roleName",
          "filters": [
           "oed",
           "oed-events",
           "oed-declaration"
          ],
          "operator": "eq"
         }
        ],
        "metricName": "requests/failed",
        "metricNamespace": "microsoft.insights/components",
        "region": "norwayeast",
        "resources": [
         {
          "metricNamespace": "Microsoft.Insights/components",
          "region": "norwayeast",
          "resourceGroup": "monitor-digdir-tt02-rg",
          "resourceName": "digdir-tt02-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      },
      {
       "azureMonitor": {
        "aggregation": "Count",
        "alias": "Failed requests oed-authz",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "requests/failed",
        "metricNamespace": "microsoft.insights/components",
        "region": "westeurope",
        "resources": [
         {
          "metricNamespace": "microsoft.insights/components",
          "region": "westeurope",
          "resourceGroup": "altinn-digdir-oed-tt02-rg",
          "resourceName": "oed-test-authz-ai",
          "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
         }
        ],
        "timeGrain": "auto"
       },
       "subscription": "7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103"
      }
     ]
    },
    {
     "title": "DAN requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "customMetrics\r\n| where name startswith \"altinn_app_oed_dan_request\"\r\n| project timestamp, value, customDimensions.dataSetName\r\n| summarize sum(value) by bin(timestamp, 1m), tostring(customDimensions_dataSetName)\r\n//| project timestamp, sum_value, customDimensions_dataSetName\r\n| project-rename _=sum_value\r\n| order by timestamp asc",
        "resources": [
         "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
        ],
        "resultFormat": "time_series"
       }
      }
     ]
    },
    {
     "title": "DAN response time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": true,
        "query": "customMetrics\r\n| where name == \"altinn_app_oed_dan_responsetime\"\r\n| project timestamp, avg=(valueSum/valueCount), customDimensions.dataSetName\r\n//| project timestamp, avg=(valueSum/valueCount), min=valueMin, max=valueMax, customDimensions.dataSetName\r\n//| summarize sum(value) by bin(timestamp, 1m), tostring(customDimensions_dataSetName)\r\n//| project timestamp, sum_value, customDimensions_dataSetName\r\n//| project-rename _=sum_value\r\n| order by timestamp asc ",
        "resources": [
         "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
        ],
        "resultFormat": "time_series",
        "timeColumn": "timestamp"
       }
      }
     ]
    },
    {
     "title": "DAN errors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "azureLogAnalytics": {
        "dashboardTime": false,
        "query": "customMetrics\r\n| where name startswith \"altinn_app_oed_dan_error\"\r\n| project timestamp, value, customDimensions.dataSetName\r\n| summarize sum(value) by bin(timestamp, 1m), tostring(customDimensions_dataSetName)\r\n//| project timestamp, sum_value, customDimensions_dataSetName\r\n| project-rename _=sum_value\r\n| order by timestamp asc",
        "resources": [
         "/subscriptions/7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103/resourceGroups/monitor-digdir-tt02-rg/providers/Microsoft.Insights/components/digdir-tt02-ai"
        ],
        "resultFormat": "time_series"
       }
      }
     ]
    }
   ]
  }
 ]
}