{
 "title": "Exceptions & Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Stacked overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of exceptions",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AppExceptions\r\n| where SeverityLevel >2 and AppRoleName in (\"oed\", \"oed-declaration\", \"oed-events\") and TimeGenerated >= $__timeFrom and TimeGenerated <= $__timeTo\r\n| summarize Errors = count() by AppRoleName, bin(TimeGenerated, 5m)\r\n| order by bin(TimeGenerated, 5m) asc",
      "resources": [
       "/subscriptions/0f05e9d4-592b-491a-b9da-49a8b242d0c5/resourceGroups/monitor-digdir-prod-rg/providers/Microsoft.OperationalInsights/workspaces/application-digdir-prod-law"
      ],
      "resultFormat": "time_series"
     }
    },
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AppExceptions\r\n| where SeverityLevel >2  and TimeGenerated >= $__timeFrom and TimeGenerated <= $__timeTo\r\n| summarize Errors = count() by AppRoleName, bin(TimeGenerated, 5m)\r\n| order by bin(TimeGenerated, 5m) asc",
      "resources": [
       "/subscriptions/0f05e9d4-592b-491a-b9da-49a8b242d0c5/resourceGroups/altinn-digdir-oed-rg/providers/Microsoft.OperationalInsights/workspaces/altinn-digdir-oed-law"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "alertlist",
   "gridPos": { "h": 20, "w": 7, "x": 12, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "allowedTimeGrainsMs": [],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Authz",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let times = range TimeGenerated from $__timeFrom() to $__timeTo() step 5m;\r\nAppExceptions\r\n| where AppRoleName contains \"authz\"\r\n      and SeverityLevel > 2\r\n      and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| summarize Exceptions = count() by bin(TimeGenerated, 5m), AppRoleName\r\n| join kind=rightouter (\r\n    times\r\n) on TimeGenerated\r\n| project TimeGenerated, AppRoleName = coalesce(AppRoleName, \"authz\"), Exceptions = coalesce(Exceptions, 0)\r\n| order by TimeGenerated asc\r\n",
      "resources": [
       "/subscriptions/0f05e9d4-592b-491a-b9da-49a8b242d0c5/resourceGroups/altinn-digdir-oed-rg/providers/Microsoft.OperationalInsights/workspaces/altinn-digdir-oed-law"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "OED",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let times = range TimeGenerated from $__timeFrom() to $__timeTo() step 5m;\r\nAppExceptions\r\n| where AppRoleName == \"oed\"\r\n      and SeverityLevel > 2\r\n      and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| summarize Exceptions = count() by bin(TimeGenerated, 5m), AppRoleName\r\n| join kind=rightouter (\r\n    times\r\n) on TimeGenerated\r\n| project TimeGenerated, AppRoleName = coalesce(AppRoleName, \"oed\"), Exceptions = coalesce(Exceptions, 0)\r\n| order by TimeGenerated asc\r\n",
      "resources": [
       "/subscriptions/0f05e9d4-592b-491a-b9da-49a8b242d0c5/resourceGroups/monitor-digdir-prod-rg/providers/Microsoft.OperationalInsights/workspaces/application-digdir-prod-law"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Events",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let times = range TimeGenerated from $__timeFrom() to $__timeTo() step 5m;\r\nAppExceptions\r\n| where AppRoleName == \"oed-events\"\r\n      and SeverityLevel > 2\r\n      and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| summarize Exceptions = count() by bin(TimeGenerated, 5m), AppRoleName\r\n| join kind=rightouter (\r\n    times\r\n) on TimeGenerated\r\n| project TimeGenerated, AppRoleName = coalesce(AppRoleName, \"oed-events\"), Exceptions = coalesce(Exceptions, 0)\r\n| order by TimeGenerated asc\r\n",
      "resources": [
       "/subscriptions/0f05e9d4-592b-491a-b9da-49a8b242d0c5/resourceGroups/monitor-digdir-prod-rg/providers/Microsoft.OperationalInsights/workspaces/application-digdir-prod-law"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Declaration",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let times = range TimeGenerated from $__timeFrom() to $__timeTo() step 5m;\r\nAppExceptions\r\n| where AppRoleName contains \"oed-declaration\"\r\n      and SeverityLevel > 2\r\n      and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| summarize Exceptions = count() by bin(TimeGenerated, 5m), AppRoleName\r\n| join kind=rightouter (\r\n    times\r\n) on TimeGenerated\r\n| project TimeGenerated, AppRoleName = coalesce(AppRoleName, \"oed-declaration\"), Exceptions = coalesce(Exceptions, 0)\r\n| order by TimeGenerated asc\r\n",
      "resources": [
       "/subscriptions/0f05e9d4-592b-491a-b9da-49a8b242d0c5/resourceGroups/monitor-digdir-prod-rg/providers/Microsoft.OperationalInsights/workspaces/application-digdir-prod-law"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "Feedpoller",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let times = range TimeGenerated from $__timeFrom() to $__timeTo() step 5m;\r\nAppExceptions\r\n| where AppRoleName contains \"feedpoller\"\r\n      and SeverityLevel > 2\r\n      and TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\r\n| summarize Exceptions = count() by bin(TimeGenerated, 5m), AppRoleName\r\n| join kind=rightouter (\r\n    times\r\n) on TimeGenerated\r\n| project TimeGenerated, AppRoleName = coalesce(AppRoleName, \"feedpoller\"), Exceptions = coalesce(Exceptions, 0)\r\n| order by TimeGenerated asc\r\n",
      "resources": [
       "/subscriptions/0f05e9d4-592b-491a-b9da-49a8b242d0c5/resourceGroups/altinn-digdir-oed-rg/providers/Microsoft.OperationalInsights/workspaces/altinn-digdir-oed-law"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  }
 ]
}