name: altinn-digdir-oed-tt02-rg

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/altinn-digdir-oed-tt02-rg.yml
      - infra/altinn-digdir-oed-tt02-rg/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/altinn-digdir-oed-tt02-rg.yml
      - infra/altinn-digdir-oed-tt02-rg/**
  workflow_dispatch:
    inputs:
      log_level:
        required: true
        description: Terraform Log Level
        default: INFO
        type: choice
        options:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR

env:
  ENVIRONMENT: test
  TF_STATE_NAME: altinn-digdir-oed-tt02-rg.tfstate
  TF_PROJECT: ./infra/altinn-digdir-oed-tt02-rg
  ARM_CLIENT_ID: ${{ vars.TF_AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: 7b6f8f15-3a3e-43a2-b6ac-8eb6c06ad103

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  plan:
    name: Plan
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Plan
        uses: altinn/altinn-platform/actions/terraform/plan@main
        with:
          working_directory: ${{ env.TF_PROJECT }}
          oidc_type: environment
          oidc_value: ${{ env.ENVIRONMENT }}
          arm_client_id: ${{ env.ARM_CLIENT_ID }}
          arm_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
          tf_state_name: ${{ env.TF_STATE_NAME }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tf_version: latest

  deploy:
    name: Deploy
    environment: test
    if: github.ref == 'refs/heads/main'
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Apply
        uses: altinn/altinn-platform/actions/terraform/apply@main
        with:
          working_directory: ${{ env.TF_PROJECT }}
          oidc_type: environment
          oidc_value: ${{ env.ENVIRONMENT }}
          arm_client_id: ${{ env.ARM_CLIENT_ID }}
          arm_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
          tf_state_name: ${{ env.TF_STATE_NAME }}
          tf_version: latest
